import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { cn } from "@/util/utils";
import ScrollFix from "@/components/ScrollFix";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ScrollFix />
      <body className={cn(montserrat.className, "bg-slate-100 text-zinc-950")}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
